[project]
name = "py_continuous_batching"
version = "2024.2.0.0"
description = "Convert tokenizers into OpenVINO models"
requires-python = ">=3.8"
readme = {file = "../../../../../README.md", content-type="text/markdown"}
license = {text = "OSI Approved :: Apache Software License"}

authors = [
    { name = "OpenVINO Developers", email = "openvino@intel.com" },
]

classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    # support of nightly openvino packages with dev suffix
    "openvino~=2024.1.0.0"
]

[project.optional-dependencies]
transformers = [
    "transformers[sentencepiece] >= 4.36.0",
    "tiktoken"
]
# chatglm2 custom tokenizer file imports torch, have to add torch dependency for tests
torch = [
    'torch'
]
dev = [
    "ruff",
    "bandit",
    "pytest",
    "pytest_harvest",
    "pandas",
    "openvino_tokenizers[transformers, torch]"
]
benchmark = [
    "pandas",
    "seaborn",
    "tqdm",
    "openvino_tokenizers[transformers]"
]
#  don't include fuzzing to avoid windows CI issues
fuzzing = [
    "atheris",
    "openvino_tokenizers[transformers]"
]
all = [
    "openvino_tokenizers[dev, transformers]"
]


[tool.ruff]
line-length = 119

[tool.ruff.lint]
ignore = ["C901", "E501", "E741", "W605"]
select = ["C", "E", "F", "I", "W"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"openvino_tokenizers/hf_parser.py" = ["F821"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.scikit-build]
cmake.build-type = "Release"
#cmake.args = [
#    "-DCMAKE_INSTALL_BINDIR=lib",
#    "-DCMAKE_INSTALL_LIBDIR=lib"
#]
cmake.targets = ["py_continuous_batching"]
wheel.build-tag = "000"
#wheel.packages = ["py_continuous_batching"] # my python files
wheel.install-dir = "py_continuous_batching"
wheel.py-api = "py3"
# TODO: how to get files from top folders
#wheel.license-files = ["../../../../../LICENSE", "../../../../../third-party-programs.txt", "../../../../../SECURITY.md"]
sdist.exclude = ["dist", "tests", "examples", "python/tests"]
sdist.cmake = true

[[tool.scikit-build.generate]]
path = "__version__.py"
template = '''
__version__ = "${version}"
'''

[build-system]
requires = ["scikit-build-core~=0.8.0"]
build-backend = "scikit_build_core.build"